# Cloud Build configuration for ADK Financial Fraud Detection System v2
# Full-stack deployment with React frontend and Python backend

steps:
  # Step 1: Build React Frontend
  - name: 'node:18-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd frontend
        npm ci --only=production
        npm run build
        ls -la dist/
    id: 'build-frontend'

  # Step 2: Build Docker image with frontend and backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/fraud-detection-v2:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/fraud-detection-v2:latest'
      - '.'
    id: 'build-docker-image'
    waitFor: ['build-frontend']

  # Step 3: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/fraud-detection-v2:$BUILD_ID'
    id: 'push-docker-image'
    waitFor: ['build-docker-image']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fraud-detection-v2'
      - '--image'
      - 'gcr.io/$PROJECT_ID/fraud-detection-v2:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,PROJECT_ID=$PROJECT_ID,REGION=us-central1'
      - '--timeout'
      - '3600'
      - '--concurrency'
      - '80'
    id: 'deploy-cloud-run'
    waitFor: ['push-docker-image']

# Configuration
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

# Artifacts
images:
  - 'gcr.io/$PROJECT_ID/fraud-detection-v2:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/fraud-detection-v2:latest'

# Timeout
timeout: '1200s'

# Substitutions for variables
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'fraud-detection-v2'